### ISSUE TITLE
Cannot find engine 

### ISSUE THREAD

**Issue by astadolfo3** [kapilratnani/django_hana#25]
I've configured the settings.py as indicated and it looks like it's not recognizing the engine. I've tried also with django.db.backends.django_hana with the same results. Any hints?

'data_source': {
        'ENGINE':'django_hana',
        'NAME': 'IOT',
        'USER': 'ALEX',
        'PASSWORD': 'PASSWORD',
        'HOST': '186.47.255.17',
        'PORT': '30015',
    }

I'm getting the error:
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f296919b320>
Traceback (most recent call last):
  File "/home/django/Env/product/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/home/django/Env/product/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/django/Env/product/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/django/Env/product/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/django/Env/product/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/django/Env/product/lib/python2.7/site-packages/django/db/models/base.py", line 1172, in check
    errors.extend(cls._check_long_column_names())
  File "/home/django/Env/product/lib/python2.7/site-packages/django/db/models/base.py", line 1587, in _check_long_column_names
    connection = connections[db]
  File "/home/django/Env/product/lib/python2.7/site-packages/django/db/utils.py", line 212, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/django/Env/product/lib/python2.7/site-packages/django/db/utils.py", line 135, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_hana' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: cannot import name BaseDatabaseOperations
^C(product) django@ip-172-31-63-203:~/product>
(product) django@ip-172-31-63-203:~/product> python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
.

**Comment by adilmalik393** [comment]
Any there any solution to the problem ?

**Comment by kapilratnani** [comment]
Sorry, the work on this extension is discontinued. Refer this blog post to use HANA with django
https://www.sap.com/india/developer/tutorials/hxe-python-django-polls.html
